# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f1a9275b2ac223298cd55172e39dd4798b118988e7efc21a2f30e2a936a947dd134a8e371b40f65e0be08e96d229567a6f6e0d7d23962cfd7fe06d6c3014ee6

test:
  secret_key_base: d9fe27db986f2fe1bbed6e4c5453730570bed1d65c2b493650703aa816a76e74fc3f7ce76d5f11a2e51f5a4b918bd70d576f71221dc95a1913f065ddbc85654c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
